name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ''
          source: '.'
          target: '/root/aztroTurbo'

      - name: Pulling project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ''
          script: |
            cd /root/aztroTurbo
            git pull https://${{secrets.PAT}}@github.com/nberthou/aztroTurbo.git main
            yarn install --frozen-lockfile
            yarn workspaces foreach -A install

      - name: Building project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ''
          script: |
            cd /root/aztroTurbo
            yarn build

      - name: Restarting app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ''
          script: |
            cd /root/aztroTurbo
            yarn workspace @repo/db prisma generate
            pm2 restart aztroTurbo  --cron "0 */3 * * *"
